### ISSUE TITLE
Uncredited MMJ code in recent commits

### ISSUE THREAD

**Issue by OpenSauce04** [mandarine3ds/mandarine#92]
### Issue

These two commits appear to use very large sections of uncredited Citra MMJ code with no credit back to the original author: 11c7211, 6f4ad12.
Please update the commits to credit the person/people who wrote the code using the co-author feature.

**Comment by Gamer64ytb** [comment]
It's a temporal branch, that's why there are no credits. When I have finished this, I'll delete branch and merge to master with weihuoya coauthoring.

**Comment by OpenSauce04** [comment]
There is no reason to type 3 words to make sure that the original author is attributed when you already spent the time converting their Java code to Kotlin. You have been caught doing this multiple times in the master branch and elsewhere, so I would advise that it's good to get into the habit of crediting people for their work.

**Comment by Fafner1000** [comment]
> It's a temporal branch, that's why there are no credits. When I have finished this, I'll delete branch and merge to master with weihuoya coauthoring.

You just never learn, time and time again doing the same thing, just do it even if it is a temporary branch.
